Hasuro-R/HASURO_portfolio

src/app/page.tsx, src/components/Index/IndexBox.tsx, src/components/Index/index.module.scss, src/components/home/TopIndex.tsx, src/components/home/home.module.scss, src/lib/index/index.ts
=> add: index #1

src/lib/index/index.ts
=> hotfix: url #3

src/components/home/AboutMe.tsx, src/components/home/about/Profile.tsx, src/lib/profile/returnAge.ts
=> fix: change age #7

src/components/home/timeline/MainTimeline.tsx, src/components/timeline/TimelineBox.tsx, src/components/timeline/timeline.module.scss, src/lib/timeline/timelineCategoryes.ts, src/lib/timeline/timelines.ts
=> add: award timeline #11

README.md
=> add: README #13

README.md
=> update: README #15

README.md
=> fix: README title #17

src/components/timeline/TimelineBox.tsx, src/lib/timeline/timelines.ts
=> add: irpc data #19

src/app/about/page.tsx, src/app/timeline/page.tsx
=> fix: twitter card kind #21

src/components/home/timeline/MainTimeline.tsx, src/components/timeline/TimelineBox.tsx, src/lib/timeline/timelineCategoryes.ts, src/lib/timeline/timelines.ts, src/lib/work/returnTech.ts
=> add: writing category #25

src/lib/timeline/timelines.ts
=> add: timeline #27

src/middleware/ColorThemeProvider.tsx
=> fix: change default theme #30

src/components/home/timeline/MainTimeline.tsx, src/components/timeline/TimelineBox.tsx, src/lib/timeline/timelines.ts, src/lib/work/returnTech.ts
=> add: timeline 2024 #34

src/components/home/timeline/MainTimeline.tsx, src/lib/timeline/timelineCategoryes.ts
=> add: timeline categoryes #37

src/lib/timeline/timelines.ts
=> add: irori works #39

src/components/home/AboutMe.tsx
=> fix: change about me #42

src/components/home/AboutMe.tsx, src/components/home/about/Profile.tsx, src/lib/profile/profileIntroduction.ts
=> add: profile text component #47

src/components/footer/Footer.tsx
=> chore: fix copylight #51

src/components/account/AccountBoxes.tsx
=> chore: change github username #53

src/components/home/about/Contact.tsx
=> fix: change email #55

src/components/home/Timeline.tsx, src/components/home/timeline/MainTimeline.tsx, src/lib/timeline/timelines.ts
=> add: timeline #58

src/components/home/Timeline.tsx, src/components/timeline/TimelineBox.tsx, src/components/timeline/timeline.module.scss
=> fix: timeline ui #50

src/app/about/page.tsx, src/app/page.module.scss, src/app/page.tsx, src/app/timeline/page.tsx, src/components/Index/IndexBox.tsx, src/components/Index/index.module.scss, src/components/UI/button/ReadMoreTextButton.tsx, src/components/UI/button/button.module.scss, src/components/home/AboutMe.tsx, src/components/home/Timeline.tsx, src/components/home/TopIndex.tsx, src/components/home/home.module.scss, src/components/timeline/timeline.module.scss, src/components/work/work.module.scss, src/lib/timeline/timelines.ts
=> fix: ui #61

src/components/UI/button/button.module.scss, src/components/timeline/timeline.module.scss, src/lib/profile/profileIntroduction.ts
=> fix: update profile

package-lock.json, package.json, src/app/page.tsx, src/components/header/Header.tsx
=> add: inoren.me #70

src/lib/timeline/timelines.ts, src/lib/work/returnTech.ts
=> add: svelte #72

package-lock.json, package.json, src/app/globals.scss, src/app/page.module.scss, src/components/Index/index.module.scss, src/components/UI/button/ReadMoreButton.tsx, src/components/UI/button/button.module.scss, src/components/UI/menu/menu.module.scss, src/components/account/AccountBoxes.tsx, src/components/account/account.module.scss, src/components/home/AboutMe.tsx, src/components/home/home.module.scss, src/components/timeline/TimelineCategory.tsx, src/components/timeline/timeline.module.scss
=> add: update ui

src/components/account/AccountBoxes.tsx, src/components/account/account.module.scss
=> add: linkedin #78

biome.json, package-lock.json, package.json, src/app/layout.tsx, src/components/UI/menu/HoverMenu.module.scss, src/components/UI/menu/HoverMenu.tsx, src/components/header/SubHeader.tsx, src/components/home/AboutMe.tsx, src/components/home/Timeline.tsx, src/components/home/Works.tsx, src/components/timeline/TimelineCategory.tsx, src/components/timeline/timeline.module.scss, src/i18n/en.json, src/i18n/ja.json, src/middleware/ColorThemeProvider.tsx
=> Feature/create main menu #85
